create table movies (
	id INT,
	title VARCHAR(100),
	year INT,
	genre VARCHAR(50),
	description TEXT,
	director VARCHAR(50),
	actors VARCHAR(50),
	runtime INT,
	rating DECIMAL(3,1),
	votes INT,
	box_office_revenue BIGINT,
	metascore INT
);
insert into movies (id, title, year, genre, description, director, actors, runtime, rating, votes, box_office_revenue, metascore) values (1, 'Fast and the Furious: Tokyo Drift', 2014, 'Action, Crime, Drama, Thriller', 'Vivamus in felis eu sapien cursus vestibulum.', 'Noellyn Jorcke', 'Yasmin Yolanda', 35, 4.3, 930469, 2667986770, 8);
insert into movies (id, title, year, genre, description, director, actors, runtime, rating, votes, box_office_revenue, metascore) values (2, 'Anatahan', 2016, 'Drama, War', 'Proin eu mi. Nulla ac enim. In tempor, turpis nec euismod scelerisque, quam turpis adipiscing lorem, vitae mattis nibh ligula nec sem. Duis aliquam convallis nunc.', 'Frederic Northcote', 'Jacob James', 65, 4.3, 825837, 4609988699, 30);
insert into movies (id, title, year, genre, description, director, actors, runtime, rating, votes, box_office_revenue, metascore) values (3, 'The Search for Santa Paws', 2015, 'Adventure, Children', 'Praesent blandit. Nam nulla. Integer pede justo, lacinia eget, tincidunt eget, tempus vel, pede.', 'Grenville McNamara', 'Olivia Olivia', 107, 5.7, 561140, 1494803851, 3);
insert into movies (id, title, year, genre, description, director, actors, runtime, rating, votes, box_office_revenue, metascore) values (4, 'Disraeli', 2003, 'Drama', 'Aliquam erat volutpat. In congue. Etiam justo.', 'Eunice Cecchetelli', 'Xander Xavier', 64, 7.3, 119214, 7933972292, 18);
insert into movies (id, title, year, genre, description, director, actors, runtime, rating, votes, box_office_revenue, metascore) values (5, 'Innocent Man, An', 2019, 'Crime, Drama', 'Duis bibendum. Morbi non quam nec dui luctus rutrum.', 'Tobie Hugo', 'Parker Peyton', 123, 1.2, 83976, 5417514296, 41);
insert into movies (id, title, year, genre, description, director, actors, runtime, rating, votes, box_office_revenue, metascore) values (6, 'Citizen Dog ', 2017, 'Comedy, Fantasy, Romance', 'Curabitur convallis. Duis consequat dui nec nisi volutpat eleifend. Donec ut dolor. Morbi vel lectus in quam fringilla rhoncus.', 'Eadie Defau', 'Isabella Ivy', 33, 1.3, 620743, 6392862886, 90);
insert into movies (id, title, year, genre, description, director, actors, runtime, rating, votes, box_office_revenue, metascore) values (7, 'Laura', 2019, 'Crime, Film-Noir, Mystery', 'In eleifend quam a odio.', 'Romain Ten Broek', 'Daniel David', 82, 7.3, 32791, 6482792224, 74);
insert into movies (id, title, year, genre, description, director, actors, runtime, rating, votes, box_office_revenue, metascore) values (8, 'Callas Forever', 2008, 'Drama', 'Vestibulum rutrum rutrum neque. Aenean auctor gravida sem.', 'Delano Klyner', 'Katherine Kylie', 73, 3.4, 849463, 8818344124, 52);
insert into movies (id, title, year, genre, description, director, actors, runtime, rating, votes, box_office_revenue, metascore) values (9, 'One A.M.', 2001, 'Comedy', 'Vivamus in felis eu sapien cursus vestibulum.', 'Geordie Lively', 'Abigail Amelia', 21, 9.0, 327566, 5017273405, 48);
insert into movies (id, title, year, genre, description, director, actors, runtime, rating, votes, box_office_revenue, metascore) values (10, 'Samaritan', 2004, 'Drama, Thriller', 'Donec semper sapien a libero.', 'Monique Baily', 'Olivia Olivia', 23, 7.9, 113184, 7248437703, 54);
insert into movies (id, title, year, genre, description, director, actors, runtime, rating, votes, box_office_revenue, metascore) values (11, 'Harvest (Stadt Land Fluss)', 2008, 'Drama, Romance', 'In hac habitasse platea dictumst. Morbi vestibulum, velit id pretium iaculis, diam erat fermentum justo, nec condimentum neque sapien placerat ante.', 'Virgie Tax', 'Connor Caleb', 7, 3.4, 983005, 5504474003, 91);
insert into movies (id, title, year, genre, description, director, actors, runtime, rating, votes, box_office_revenue, metascore) values (12, 'Orphan', 2018, 'Drama, Horror, Mystery, Thriller', 'Lorem ipsum dolor sit amet, consectetuer adipiscing elit.', 'Oswell Boyington', 'Abigail Amelia', 101, 7.0, 906451, 9417509125, 67);
insert into movies (id, title, year, genre, description, director, actors, runtime, rating, votes, box_office_revenue, metascore) values (13, 'Lumberjacking (Nuoruuteni savotat)', 2002, 'Drama', 'Nam nulla. Integer pede justo, lacinia eget, tincidunt eget, tempus vel, pede. Morbi porttitor lorem id ligula. Suspendisse ornare consequat lectus.', 'Zora Focke', 'Yasmin Yolanda', 48, 6.4, 916851, 5194347515, 91);
insert into movies (id, title, year, genre, description, director, actors, runtime, rating, votes, box_office_revenue, metascore) values (14, 'So Fine', 2015, 'Comedy', 'Donec ut mauris eget massa tempor convallis. Nulla neque libero, convallis eget, eleifend luctus, ultricies eu, nibh. Quisque id justo sit amet sapien dignissim vestibulum.', 'Thaxter Hastin', 'Ursula Una', 24, 4.5, 444920, 9045743115, 43);
insert into movies (id, title, year, genre, description, director, actors, runtime, rating, votes, box_office_revenue, metascore) values (15, 'Thieves by Law (Ganavim Ba Hok)', 2009, 'Documentary', 'Mauris ullamcorper purus sit amet nulla. Quisque arcu libero, rutrum ac, lobortis vel, dapibus at, diam. Nam tristique tortor eu pede.', 'Gerda Callister', 'Jacob James', 49, 6.2, 232693, 3114574558, 35);
insert into movies (id, title, year, genre, description, director, actors, runtime, rating, votes, box_office_revenue, metascore) values (16, 'Ten Shrews', 2013, 'Comedy', 'Maecenas tristique, est et tempus semper, est quam pharetra magna, ac consequat metus sapien ut nunc. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Mauris viverra diam vitae quam.', 'Virgil Breeds', 'Amelia Avery', 112, 2.3, 890662, 254468472, 64);
insert into movies (id, title, year, genre, description, director, actors, runtime, rating, votes, box_office_revenue, metascore) values (17, 'Intervista', 2016, 'Comedy, Drama', 'Duis bibendum, felis sed interdum venenatis, turpis enim blandit mi, in porttitor pede justo eu massa. Donec dapibus. Duis at velit eu est congue elementum. In hac habitasse platea dictumst.', 'Elisabet Chastagnier', 'Isabella Ivy', 109, 2.2, 498295, 4930551586, 75);
insert into movies (id, title, year, genre, description, director, actors, runtime, rating, votes, box_office_revenue, metascore) values (18, 'H6: Diario de un asesino', 2016, 'Horror, Thriller', 'Morbi porttitor lorem id ligula.', 'Sean Colbrun', 'Liam Lucas', 77, 3.3, 416969, 1702412703, 14);
insert into movies (id, title, year, genre, description, director, actors, runtime, rating, votes, box_office_revenue, metascore) values (19, 'Here and Elsewhere', 2019, 'Documentary', 'Nulla ac enim. In tempor, turpis nec euismod scelerisque, quam turpis adipiscing lorem, vitae mattis nibh ligula nec sem. Duis aliquam convallis nunc.', 'Gipsy Rowly', 'Dylan Dominic', 16, 6.9, 655740, 1829128312, 8);
insert into movies (id, title, year, genre, description, director, actors, runtime, rating, votes, box_office_revenue, metascore) values (20, 'Brothers Rico, The', 2011, 'Crime, Drama, Film-Noir, Thriller', 'Integer ac neque. Duis bibendum.', 'Niven Drewry', 'Parker Peyton', 112, 1.5, 855404, 6097000793, 25);
insert into movies (id, title, year, genre, description, director, actors, runtime, rating, votes, box_office_revenue, metascore) values (21, 'Girl Can''t Help It, The', 2002, 'Comedy', 'Donec posuere metus vitae ipsum. Aliquam non mauris. Morbi non lectus.', 'Gabriella Cicconetti', 'Jacob James', 25, 6.1, 605984, 7795985913, 74);
insert into movies (id, title, year, genre, description, director, actors, runtime, rating, votes, box_office_revenue, metascore) values (22, 'Billu', 2013, 'Comedy, Drama, Musical', 'Cras in purus eu magna vulputate luctus. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Vivamus vestibulum sagittis sapien. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus.', 'Therine Doag', 'Liam Lucas', 14, 7.9, 131450, 4131150342, 73);
insert into movies (id, title, year, genre, description, director, actors, runtime, rating, votes, box_office_revenue, metascore) values (23, 'Satan''s Brew ', 2008, 'Comedy, Drama', 'Nulla suscipit ligula in lacus. Curabitur at ipsum ac tellus semper interdum. Mauris ullamcorper purus sit amet nulla. Quisque arcu libero, rutrum ac, lobortis vel, dapibus at, diam.', 'Tallia Rzehor', 'Zachary Zane', 51, 8.0, 628294, 7703202371, 57);
insert into movies (id, title, year, genre, description, director, actors, runtime, rating, votes, box_office_revenue, metascore) values (24, 'Chorus', 2003, 'Drama', 'Integer non velit.', 'Jodie Beckett', 'Amelia Avery', 107, 2.4, 590668, 5909485883, 64);
insert into movies (id, title, year, genre, description, director, actors, runtime, rating, votes, box_office_revenue, metascore) values (25, 'Day the Fish Came Out', 2011, 'Comedy, Sci-Fi', 'Curabitur convallis.', 'Almeria Scarsbrick', 'Ursula Una', 53, 1.8, 180, 9278746594, 33);
insert into movies (id, title, year, genre, description, director, actors, runtime, rating, votes, box_office_revenue, metascore) values (26, 'Raw Deal', 2015, 'Action', 'Proin eu mi.', 'Maisey Dallaghan', 'Noah Nathaniel', 10, 7.7, 203835, 6404421382, 39);
insert into movies (id, title, year, genre, description, director, actors, runtime, rating, votes, box_office_revenue, metascore) values (27, 'Lady Be Good', 2014, 'Comedy, Musical', 'Etiam pretium iaculis justo. In hac habitasse platea dictumst. Etiam faucibus cursus urna. Ut tellus.', 'Benni Benedtti', 'Katherine Kylie', 94, 3.8, 66504, 1517558539, 84);
insert into movies (id, title, year, genre, description, director, actors, runtime, rating, votes, box_office_revenue, metascore) values (28, 'Frozen', 2017, 'Drama', 'Pellentesque viverra pede ac diam.', 'Caitrin Rowlands', 'Katherine Kylie', 70, 4.8, 841074, 6717058915, 77);
insert into movies (id, title, year, genre, description, director, actors, runtime, rating, votes, box_office_revenue, metascore) values (29, 'Little Witches', 2008, 'Horror, Thriller', 'Praesent blandit.', 'Gordan Lote', 'Quinn Quinn', 10, 8.0, 791886, 6098955562, 52);
insert into movies (id, title, year, genre, description, director, actors, runtime, rating, votes, box_office_revenue, metascore) values (30, 'Beau Pere', 2010, 'Drama', 'In hac habitasse platea dictumst. Etiam faucibus cursus urna. Ut tellus. Nulla ut erat id mauris vulputate elementum.', 'Chrotoem Strugnell', 'Yasmin Yolanda', 108, 1.2, 297012, 9064308016, 26);
insert into movies (id, title, year, genre, description, director, actors, runtime, rating, votes, box_office_revenue, metascore) values (31, 'Hunky Dory', 2006, 'Drama, Musical', 'Curabitur gravida nisi at nibh. In hac habitasse platea dictumst. Aliquam augue quam, sollicitudin vitae, consectetuer eget, rutrum at, lorem.', 'Ermanno Chimes', 'Grace Gabrielle', 80, 5.8, 819554, 322170111, 75);
insert into movies (id, title, year, genre, description, director, actors, runtime, rating, votes, box_office_revenue, metascore) values (32, 'I''m Not Rappaport', 2006, 'Comedy', 'Morbi porttitor lorem id ligula. Suspendisse ornare consequat lectus. In est risus, auctor sed, tristique in, tempus sit amet, sem.', 'Rowney Jakeway', 'Willow Wren', 53, 1.9, 662523, 827383108, 14);
insert into movies (id, title, year, genre, description, director, actors, runtime, rating, votes, box_office_revenue, metascore) values (33, 'McCullochs, The', 2004, 'Drama', 'Proin risus. Praesent lectus. Vestibulum quam sapien, varius ut, blandit non, interdum in, ante. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Duis faucibus accumsan odio.', 'Tamas Leguay', 'Riley Rachel', 18, 8.6, 415367, 7396764683, 47);
insert into movies (id, title, year, genre, description, director, actors, runtime, rating, votes, box_office_revenue, metascore) values (34, 'Fire and Ice', 2002, 'Animation, Fantasy', 'In eleifend quam a odio. In hac habitasse platea dictumst. Maecenas ut massa quis augue luctus tincidunt. Nulla mollis molestie lorem.', 'Rosalind Pingston', 'Amelia Avery', 102, 9.9, 245967, 8161264907, 78);
insert into movies (id, title, year, genre, description, director, actors, runtime, rating, votes, box_office_revenue, metascore) values (35, 'Hearts of the West', 2009, 'Comedy, Western', 'Nullam sit amet turpis elementum ligula vehicula consequat. Morbi a ipsum. Integer a nibh.', 'Janice Burchatt', 'Benjamin Blake', 21, 4.7, 1748, 4227842060, 3);
insert into movies (id, title, year, genre, description, director, actors, runtime, rating, votes, box_office_revenue, metascore) values (36, 'Mr. Jones', 2017, 'Drama, Horror, Thriller', 'Nam dui.', 'Faulkner Routham', 'Zachary Zane', 84, 1.7, 2663, 805035731, 18);
insert into movies (id, title, year, genre, description, director, actors, runtime, rating, votes, box_office_revenue, metascore) values (37, 'Strangers on a Train', 2003, 'Crime, Drama, Film-Noir, Thriller', 'Duis ac nibh. Fusce lacus purus, aliquet at, feugiat non, pretium quis, lectus. Suspendisse potenti. In eleifend quam a odio.', 'Ange Hansell', 'Liam Lucas', 64, 6.2, 558812, 8230832440, 53);
insert into movies (id, title, year, genre, description, director, actors, runtime, rating, votes, box_office_revenue, metascore) values (38, 'Adventures of Ichabod and Mr. Toad', 2013, 'Animation, Children', 'Cras pellentesque volutpat dui. Maecenas tristique, est et tempus semper, est quam pharetra magna, ac consequat metus sapien ut nunc. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Mauris viverra diam vitae quam.', 'Maddie Moodey', 'Thomas Tyler', 36, 4.6, 448347, 8070587623, 48);
insert into movies (id, title, year, genre, description, director, actors, runtime, rating, votes, box_office_revenue, metascore) values (39, 'Milk Money', 2006, 'Comedy, Romance', 'Morbi non lectus. Aliquam sit amet diam in magna bibendum imperdiet. Nullam orci pede, venenatis non, sodales sed, tincidunt eu, felis. Fusce posuere felis sed lacus.', 'Opalina Orbell', 'Noah Nathaniel', 89, 1.6, 610501, 6738936223, 52);
insert into movies (id, title, year, genre, description, director, actors, runtime, rating, votes, box_office_revenue, metascore) values (40, 'Magic Voyage of Sindbad', 2005, 'Adventure, Fantasy', 'Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Etiam vel augue. Vestibulum rutrum rutrum neque. Aenean auctor gravida sem.', 'Omero Babe', 'Ursula Una', 20, 3.8, 621370, 5229897230, 50);
insert into movies (id, title, year, genre, description, director, actors, runtime, rating, votes, box_office_revenue, metascore) values (41, 'Pyramid of Triboulet', 2016, 'Fantasy', 'Praesent blandit lacinia erat. Vestibulum sed magna at nunc commodo placerat.', 'Paloma Rubenfeld', 'Parker Peyton', 124, 9.0, 187675, 4352688637, 24);
insert into movies (id, title, year, genre, description, director, actors, runtime, rating, votes, box_office_revenue, metascore) values (42, 'When I Grow Up, I''ll Be a Kangaroo', 2013, 'Comedy', 'Aliquam non mauris.', 'Ertha Rigg', 'Zachary Zane', 28, 5.1, 337008, 5485105101, 89);
insert into movies (id, title, year, genre, description, director, actors, runtime, rating, votes, box_office_revenue, metascore) values (43, 'Meat the Truth', 2009, 'Documentary', 'Quisque ut erat. Curabitur gravida nisi at nibh. In hac habitasse platea dictumst.', 'Tabbie Errol', 'Katherine Kylie', 47, 5.6, 52224, 9691685381, 100);
insert into movies (id, title, year, genre, description, director, actors, runtime, rating, votes, box_office_revenue, metascore) values (44, 'Random Harvest', 2012, 'Drama, Romance', 'Pellentesque ultrices mattis odio. Donec vitae nisi. Nam ultrices, libero non mattis pulvinar, nulla pede ullamcorper augue, a suscipit nulla elit ac nulla.', 'Baxie Thurner', 'Olivia Olivia', 24, 8.4, 738235, 9083881477, 23);
insert into movies (id, title, year, genre, description, director, actors, runtime, rating, votes, box_office_revenue, metascore) values (45, 'Everyone Says I Love You', 2005, 'Comedy, Musical, Romance', 'Nunc nisl. Duis bibendum, felis sed interdum venenatis, turpis enim blandit mi, in porttitor pede justo eu massa. Donec dapibus.', 'Tommy Vanshin', 'Aiden Alexander', 34, 4.2, 526854, 1897565996, 40);
insert into movies (id, title, year, genre, description, director, actors, runtime, rating, votes, box_office_revenue, metascore) values (46, 'Possession', 2005, 'Drama, Horror, Mystery, Romance, Thriller', 'Pellentesque viverra pede ac diam. Cras pellentesque volutpat dui.', 'Agathe Ewbanche', 'Thomas Tyler', 31, 8.2, 77534, 9090058164, 32);
insert into movies (id, title, year, genre, description, director, actors, runtime, rating, votes, box_office_revenue, metascore) values (47, 'Romance in Manhattan', 2010, 'Comedy, Romance', 'Fusce congue, diam id ornare imperdiet, sapien urna pretium nisl, ut volutpat sapien arcu sed augue.', 'Isabel MacConneely', 'Vincent Victor', 3, 9.6, 254588, 1861599861, 8);
insert into movies (id, title, year, genre, description, director, actors, runtime, rating, votes, box_office_revenue, metascore) values (48, 'Low Life', 2019, 'Drama', 'Morbi odio odio, elementum eu, interdum eu, tincidunt in, leo.', 'Katheryn Delacourt', 'Isabella Ivy', 104, 6.2, 694514, 3528975931, 60);
insert into movies (id, title, year, genre, description, director, actors, runtime, rating, votes, box_office_revenue, metascore) values (49, 'It''s Alive', 2017, 'Horror', 'Mauris sit amet eros. Suspendisse accumsan tortor quis turpis. Sed ante.', 'Jaquelin Yerrall', 'Henry Harrison', 67, 4.1, 769791, 4731239126, 70);
insert into movies (id, title, year, genre, description, director, actors, runtime, rating, votes, box_office_revenue, metascore) values (50, 'Fresh', 2017, 'Crime, Drama, Thriller', 'Phasellus id sapien in sapien iaculis congue. Vivamus metus arcu, adipiscing molestie, hendrerit at, vulputate vitae, nisl. Aenean lectus.', 'Darwin Offield', 'Finley Finn', 86, 6.2, 232092, 3990934321, 40);
insert into movies (id, title, year, genre, description, director, actors, runtime, rating, votes, box_office_revenue, metascore) values (51, 'Robin Hood', 2009, 'Action, Adventure, Drama, Romance, War', 'Praesent id massa id nisl venenatis lacinia. Aenean sit amet justo. Morbi ut odio.', 'Massimiliano Dieton', 'Katherine Kylie', 10, 3.9, 709232, 2668358191, 15);
insert into movies (id, title, year, genre, description, director, actors, runtime, rating, votes, box_office_revenue, metascore) values (52, 'Ski Patrol', 2016, 'Action, War', 'Duis bibendum.', 'Kahlil Boulstridge', 'Benjamin Blake', 36, 7.7, 436729, 1546421665, 80);
insert into movies (id, title, year, genre, description, director, actors, runtime, rating, votes, box_office_revenue, metascore) values (53, '200 M.P.H.', 2017, 'Action, Adventure, Drama', 'Sed accumsan felis. Ut at dolor quis odio consequat varius.', 'Raynell Witcher', 'Noah Nathaniel', 75, 9.7, 998939, 2929379985, 50);
insert into movies (id, title, year, genre, description, director, actors, runtime, rating, votes, box_office_revenue, metascore) values (54, 'Wrestling for Jesus', 2010, 'Documentary', 'Aenean fermentum.', 'Joyous Moan', 'Daniel David', 107, 3.3, 839197, 1566923838, 8);
insert into movies (id, title, year, genre, description, director, actors, runtime, rating, votes, box_office_revenue, metascore) values (55, 'Make Them Die Slowly', 2010, 'Horror', 'Maecenas ut massa quis augue luctus tincidunt. Nulla mollis molestie lorem.', 'Kincaid MacFadyen', 'Daniel David', 67, 8.2, 644148, 9353107116, 47);
insert into movies (id, title, year, genre, description, director, actors, runtime, rating, votes, box_office_revenue, metascore) values (56, 'Pumpkin Eater', 2010, 'Drama', 'Vestibulum ac est lacinia nisi venenatis tristique.', 'Odille Suggate', 'Jacob James', 85, 4.8, 668425, 4118998568, 36);
insert into movies (id, title, year, genre, description, director, actors, runtime, rating, votes, box_office_revenue, metascore) values (57, 'Italian Job', 2015, 'Action, Comedy, Crime', 'Maecenas pulvinar lobortis est. Phasellus sit amet erat.', 'Tadd Burgoine', 'Emily Elizabeth', 58, 7.9, 366007, 1414473884, 35);
insert into movies (id, title, year, genre, description, director, actors, runtime, rating, votes, box_office_revenue, metascore) values (58, 'Magnificent Obsession', 2019, 'Drama, Romance', 'Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Donec pharetra, magna vestibulum aliquet ultrices, erat tortor sollicitudin mi, sit amet lobortis sapien sapien non mi.', 'Wynny Garron', 'Jacob James', 77, 7.1, 509309, 300225412, 42);
insert into movies (id, title, year, genre, description, director, actors, runtime, rating, votes, box_office_revenue, metascore) values (59, 'Crazy Heart', 2012, 'Drama, Romance', 'Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Donec pharetra, magna vestibulum aliquet ultrices, erat tortor sollicitudin mi, sit amet lobortis sapien sapien non mi. Integer ac neque.', 'Ransom Kilbourn', 'Ursula Una', 52, 1.0, 969249, 8186413118, 67);
insert into movies (id, title, year, genre, description, director, actors, runtime, rating, votes, box_office_revenue, metascore) values (60, 'Act Da Fool', 2018, '(no genres listed)', 'Quisque ut erat. Curabitur gravida nisi at nibh. In hac habitasse platea dictumst. Aliquam augue quam, sollicitudin vitae, consectetuer eget, rutrum at, lorem.', 'Sidonnie Brennenstuhl', 'Abigail Amelia', 113, 2.6, 750469, 242935113, 39);
insert into movies (id, title, year, genre, description, director, actors, runtime, rating, votes, box_office_revenue, metascore) values (61, 'Lord of the Rings: The Fellowship of the Ring, The', 2018, 'Adventure, Fantasy', 'Duis mattis egestas metus. Aenean fermentum. Donec ut mauris eget massa tempor convallis.', 'Florette Ainsworth', 'Katherine Kylie', 84, 1.3, 941527, 2435276078, 23);
insert into movies (id, title, year, genre, description, director, actors, runtime, rating, votes, box_office_revenue, metascore) values (62, 'Dead Awake', 2010, 'Fantasy, Mystery, Romance, Thriller', 'Vivamus tortor. Duis mattis egestas metus.', 'Andy Ilchuk', 'Ursula Una', 54, 5.3, 698070, 8606556518, 56);
insert into movies (id, title, year, genre, description, director, actors, runtime, rating, votes, box_office_revenue, metascore) values (63, 'Sonny Boy', 2010, 'Action, Drama, Thriller', 'Morbi quis tortor id nulla ultrices aliquet. Maecenas leo odio, condimentum id, luctus nec, molestie sed, justo.', 'Bordie Ryce', 'Katherine Kylie', 97, 2.5, 841333, 2124310146, 82);
insert into movies (id, title, year, genre, description, director, actors, runtime, rating, votes, box_office_revenue, metascore) values (64, 'Edge of Madness', 2001, 'Drama', 'Praesent blandit lacinia erat. Vestibulum sed magna at nunc commodo placerat.', 'Rafael Philipet', 'Thomas Tyler', 20, 3.4, 524953, 998443826, 7);
insert into movies (id, title, year, genre, description, director, actors, runtime, rating, votes, box_office_revenue, metascore) values (65, 'Colony, The', 2013, 'Action, Horror, Sci-Fi, Thriller', 'Morbi vel lectus in quam fringilla rhoncus.', 'Andy Cumberbatch', 'Charlotte Claire', 19, 6.2, 692553, 7963338640, 87);
insert into movies (id, title, year, genre, description, director, actors, runtime, rating, votes, box_office_revenue, metascore) values (66, 'Gloomy Sunday (Ein Lied von Liebe und Tod)', 2001, 'Drama, Romance', 'Maecenas ut massa quis augue luctus tincidunt.', 'Zonnya De Gregorio', 'Quinn Quinn', 77, 3.2, 198373, 8391093376, 49);
insert into movies (id, title, year, genre, description, director, actors, runtime, rating, votes, box_office_revenue, metascore) values (67, 'Alois Nebel', 2018, 'Animation, Crime, War', 'Vestibulum rutrum rutrum neque. Aenean auctor gravida sem. Praesent id massa id nisl venenatis lacinia. Aenean sit amet justo.', 'Tamara Bracey', 'Thomas Tyler', 67, 6.4, 617377, 5535891916, 45);
insert into movies (id, title, year, genre, description, director, actors, runtime, rating, votes, box_office_revenue, metascore) values (68, 'Amarcord', 2012, 'Comedy, Drama', 'Nulla nisl. Nunc nisl.', 'Aylmar Jancar', 'Dylan Dominic', 92, 2.4, 971163, 7954195891, 36);
insert into movies (id, title, year, genre, description, director, actors, runtime, rating, votes, box_office_revenue, metascore) values (69, 'Ewoks: The Battle for Endor', 2003, 'Adventure, Children, Fantasy, Sci-Fi', 'Morbi a ipsum. Integer a nibh. In quis justo.', 'Kristofer Soutter', 'Emily Elizabeth', 11, 4.0, 998915, 7170248404, 14);
insert into movies (id, title, year, genre, description, director, actors, runtime, rating, votes, box_office_revenue, metascore) values (70, 'Jerusalema (Gangster''s Paradise: Jerusalema)', 2016, 'Action, Crime, Drama', 'Nam ultrices, libero non mattis pulvinar, nulla pede ullamcorper augue, a suscipit nulla elit ac nulla. Sed vel enim sit amet nunc viverra dapibus. Nulla suscipit ligula in lacus. Curabitur at ipsum ac tellus semper interdum.', 'Marj Ceney', 'Riley Rachel', 52, 1.6, 286211, 3823142145, 29);
insert into movies (id, title, year, genre, description, director, actors, runtime, rating, votes, box_office_revenue, metascore) values (71, 'Angus', 2018, 'Comedy', 'Nullam molestie nibh in lectus. Pellentesque at nulla. Suspendisse potenti. Cras in purus eu magna vulputate luctus.', 'Kristina Narraway', 'Riley Rachel', 119, 5.3, 2529, 3842725167, 44);
insert into movies (id, title, year, genre, description, director, actors, runtime, rating, votes, box_office_revenue, metascore) values (72, 'Capote', 2003, 'Crime, Drama', 'Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Donec pharetra, magna vestibulum aliquet ultrices, erat tortor sollicitudin mi, sit amet lobortis sapien sapien non mi. Integer ac neque. Duis bibendum. Morbi non quam nec dui luctus rutrum.', 'Artus Gravenell', 'Yasmin Yolanda', 122, 7.8, 149680, 8999091618, 63);
insert into movies (id, title, year, genre, description, director, actors, runtime, rating, votes, box_office_revenue, metascore) values (73, 'Harry Potter and the Goblet of Fire', 2005, 'Adventure, Fantasy, Thriller, IMAX', 'In hac habitasse platea dictumst. Morbi vestibulum, velit id pretium iaculis, diam erat fermentum justo, nec condimentum neque sapien placerat ante. Nulla justo.', 'Audre Collyear', 'Zachary Zane', 94, 2.9, 402358, 3888158599, 79);
insert into movies (id, title, year, genre, description, director, actors, runtime, rating, votes, box_office_revenue, metascore) values (74, 'Shadowlands', 2018, 'Drama, Romance', 'In quis justo. Maecenas rhoncus aliquam lacus.', 'Kanya Maleby', 'Olivia Olivia', 62, 7.6, 685883, 9166494721, 37);
insert into movies (id, title, year, genre, description, director, actors, runtime, rating, votes, box_office_revenue, metascore) values (75, 'Immigrant, The', 2011, 'Drama, Romance', 'In sagittis dui vel nisl. Duis ac nibh.', 'Darwin Grzesiewicz', 'Vincent Victor', 89, 8.0, 840230, 7436824170, 58);
insert into movies (id, title, year, genre, description, director, actors, runtime, rating, votes, box_office_revenue, metascore) values (76, 'Black Sunday', 2006, 'Action, Drama, Thriller', 'Curabitur gravida nisi at nibh.', 'Claire Lars', 'Abigail Amelia', 106, 5.2, 543339, 465965327, 61);
insert into movies (id, title, year, genre, description, director, actors, runtime, rating, votes, box_office_revenue, metascore) values (77, 'Bright Days Ahead', 2001, 'Drama, Romance', 'Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Donec pharetra, magna vestibulum aliquet ultrices, erat tortor sollicitudin mi, sit amet lobortis sapien sapien non mi. Integer ac neque.', 'Wyndham De Witt', 'Charlotte Claire', 57, 2.4, 161814, 4635173, 59);
insert into movies (id, title, year, genre, description, director, actors, runtime, rating, votes, box_office_revenue, metascore) values (78, 'Election Day', 2002, 'Documentary', 'Duis consequat dui nec nisi volutpat eleifend. Donec ut dolor. Morbi vel lectus in quam fringilla rhoncus.', 'Leela Baumaier', 'Liam Lucas', 49, 7.4, 287313, 6060035307, 86);
insert into movies (id, title, year, genre, description, director, actors, runtime, rating, votes, box_office_revenue, metascore) values (79, 'White on Rice', 2010, 'Comedy', 'In tempor, turpis nec euismod scelerisque, quam turpis adipiscing lorem, vitae mattis nibh ligula nec sem. Duis aliquam convallis nunc. Proin at turpis a pede posuere nonummy. Integer non velit.', 'Marni Trevna', 'Madison Maya', 35, 6.4, 945006, 5326244186, 41);
insert into movies (id, title, year, genre, description, director, actors, runtime, rating, votes, box_office_revenue, metascore) values (80, 'Swoon', 2000, 'Crime, Drama', 'Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Nulla dapibus dolor vel est.', 'Coletta Milberry', 'Madison Maya', 110, 5.6, 885684, 2432290013, 32);
insert into movies (id, title, year, genre, description, director, actors, runtime, rating, votes, box_office_revenue, metascore) values (81, 'Container', 2017, 'Drama, Horror', 'Nunc rhoncus dui vel sem. Sed sagittis. Nam congue, risus semper porta volutpat, quam pede lobortis ligula, sit amet eleifend pede libero quis orci.', 'Jilleen Musprat', 'Aiden Alexander', 105, 4.3, 368013, 7916279332, 9);
insert into movies (id, title, year, genre, description, director, actors, runtime, rating, votes, box_office_revenue, metascore) values (82, 'Maid', 2007, 'Drama', 'Mauris lacinia sapien quis libero. Nullam sit amet turpis elementum ligula vehicula consequat.', 'Audrie Ewence', 'Amelia Avery', 45, 2.0, 602870, 1698768423, 87);
insert into movies (id, title, year, genre, description, director, actors, runtime, rating, votes, box_office_revenue, metascore) values (83, 'Cause for Alarm!', 2004, 'Crime, Drama, Film-Noir, Thriller', 'In eleifend quam a odio.', 'Mellisa Sapsed', 'Grace Gabrielle', 33, 4.3, 331633, 9202385578, 28);
insert into movies (id, title, year, genre, description, director, actors, runtime, rating, votes, box_office_revenue, metascore) values (84, 'Chance', 2009, 'Comedy, Drama', 'Nulla ac enim. In tempor, turpis nec euismod scelerisque, quam turpis adipiscing lorem, vitae mattis nibh ligula nec sem. Duis aliquam convallis nunc.', 'Ardisj Clineck', 'Connor Caleb', 108, 6.7, 881420, 2957898226, 1);
insert into movies (id, title, year, genre, description, director, actors, runtime, rating, votes, box_office_revenue, metascore) values (85, 'In Between Days', 2003, 'Drama', 'Nullam porttitor lacus at turpis.', 'Dewitt Ivashintsov', 'Henry Harrison', 16, 8.6, 42913, 7229105740, 18);
insert into movies (id, title, year, genre, description, director, actors, runtime, rating, votes, box_office_revenue, metascore) values (86, '12 Storeys', 2003, 'Comedy, Drama', 'Nulla justo.', 'Lynea Librey', 'Jacob James', 80, 8.6, 464660, 8747095782, 23);
insert into movies (id, title, year, genre, description, director, actors, runtime, rating, votes, box_office_revenue, metascore) values (87, 'Game of Death', 2003, 'Documentary', 'Nam nulla. Integer pede justo, lacinia eget, tincidunt eget, tempus vel, pede.', 'Genna Erni', 'Grace Gabrielle', 6, 4.8, 382841, 7288043210, 77);
insert into movies (id, title, year, genre, description, director, actors, runtime, rating, votes, box_office_revenue, metascore) values (88, 'Hollywood Complex', 2001, 'Documentary', 'Etiam pretium iaculis justo. In hac habitasse platea dictumst.', 'Lou Axford', 'Connor Caleb', 76, 7.2, 211222, 4432655820, 31);
insert into movies (id, title, year, genre, description, director, actors, runtime, rating, votes, box_office_revenue, metascore) values (89, 'Back Street', 2015, 'Drama', 'Nulla justo. Aliquam quis turpis eget elit sodales scelerisque. Mauris sit amet eros.', 'Devi Wennam', 'Emily Elizabeth', 77, 5.8, 299018, 3433812987, 25);
insert into movies (id, title, year, genre, description, director, actors, runtime, rating, votes, box_office_revenue, metascore) values (90, 'Age of Consent', 2009, 'Comedy, Drama, Romance', 'Aliquam sit amet diam in magna bibendum imperdiet. Nullam orci pede, venenatis non, sodales sed, tincidunt eu, felis. Fusce posuere felis sed lacus.', 'Tomaso Pywell', 'Aiden Alexander', 55, 9.1, 391619, 5954436733, 73);
insert into movies (id, title, year, genre, description, director, actors, runtime, rating, votes, box_office_revenue, metascore) values (91, 'Woman of Paris', 2005, 'Drama', 'In tempor, turpis nec euismod scelerisque, quam turpis adipiscing lorem, vitae mattis nibh ligula nec sem. Duis aliquam convallis nunc. Proin at turpis a pede posuere nonummy. Integer non velit.', 'Fedora Cumo', 'Madison Maya', 13, 3.8, 438763, 8951102065, 51);
insert into movies (id, title, year, genre, description, director, actors, runtime, rating, votes, box_office_revenue, metascore) values (92, 'Rainmaker', 2008, 'Drama', 'Curabitur at ipsum ac tellus semper interdum. Mauris ullamcorper purus sit amet nulla.', 'Deanna Haton', 'Abigail Amelia', 16, 2.4, 870690, 2683197326, 31);
insert into movies (id, title, year, genre, description, director, actors, runtime, rating, votes, box_office_revenue, metascore) values (93, 'Fancy Pants', 2013, 'Comedy, Western', 'Donec semper sapien a libero. Nam dui. Proin leo odio, porttitor id, consequat in, consequat ut, nulla. Sed accumsan felis.', 'Patti Barnby', 'Madison Maya', 39, 6.9, 258239, 4996757932, 31);
insert into movies (id, title, year, genre, description, director, actors, runtime, rating, votes, box_office_revenue, metascore) values (94, 'Jaws 2', 2018, 'Horror, Thriller', 'In tempor, turpis nec euismod scelerisque, quam turpis adipiscing lorem, vitae mattis nibh ligula nec sem. Duis aliquam convallis nunc. Proin at turpis a pede posuere nonummy.', 'Ewen Lawdham', 'Zachary Zane', 39, 9.3, 226887, 4701645847, 95);
insert into movies (id, title, year, genre, description, director, actors, runtime, rating, votes, box_office_revenue, metascore) values (95, 'Resan Till Melonia', 2014, 'Adventure, Animation, Children, Fantasy', 'Nulla justo. Aliquam quis turpis eget elit sodales scelerisque. Mauris sit amet eros. Suspendisse accumsan tortor quis turpis.', 'Rubetta Giotto', 'Willow Wren', 52, 5.1, 724306, 510279739, 79);
insert into movies (id, title, year, genre, description, director, actors, runtime, rating, votes, box_office_revenue, metascore) values (96, 'Goyokin', 2004, 'Action, Drama', 'In est risus, auctor sed, tristique in, tempus sit amet, sem. Fusce consequat.', 'Doralynn Capineer', 'Katherine Kylie', 19, 9.2, 893201, 1186883768, 21);
insert into movies (id, title, year, genre, description, director, actors, runtime, rating, votes, box_office_revenue, metascore) values (97, 'The Adventures of Tom Thumb & Thumbelina', 2008, 'Animation', 'Phasellus sit amet erat. Nulla tempus. Vivamus in felis eu sapien cursus vestibulum. Proin eu mi.', 'Farr Beavors', 'Aiden Alexander', 43, 6.4, 398354, 8737212624, 86);
insert into movies (id, title, year, genre, description, director, actors, runtime, rating, votes, box_office_revenue, metascore) values (98, 'Johnny Handsome', 2007, 'Crime, Drama', 'Duis bibendum.', 'Mel Muckian', 'Charlotte Claire', 115, 2.8, 668344, 558769979, 9);
insert into movies (id, title, year, genre, description, director, actors, runtime, rating, votes, box_office_revenue, metascore) values (99, 'Land of Happines', 2008, 'Drama', 'Curabitur convallis. Duis consequat dui nec nisi volutpat eleifend.', 'Kennan MacGilfoyle', 'Madison Maya', 19, 1.3, 14875, 5761294936, 33);
insert into movies (id, title, year, genre, description, director, actors, runtime, rating, votes, box_office_revenue, metascore) values (100, 'Venus and Serena', 2019, 'Documentary', 'Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Nulla dapibus dolor vel est.', 'Natalie Elcock', 'Zachary Zane', 125, 5.3, 757805, 7798267116, 100);
